title: jwlee51
author: leejoowon20151334
email: jwlee51@kookmin.ac.kr
description: > # this means to ignore newlines until "show_exerpts:"
  20151334 이주원<br>
  소프트웨어융합대학<br>
  2022 유레카프로젝트 과제
show_excerpts: false # set to true to show excerpts on the homepage

url: "https://leejoowon20151334.github.io/"
baseurl: ""

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # (optional) discqus comment configuration
  disqus:
    shortname: bitbrain-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://github.com/leejoowon20151334
      icon: github-square
      color: purple

  # wether the author box should be displayed
  show_author: true

  # the animation speed of the scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  #avatar_source: github
  #github_username: bitbrain
  #avatar_source: local
  #avatar_path: /assets/avatar.png

# Build settings
#theme: jekyll-dash
remote_theme: "bitbrain/jekyll-dash"

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
 - jekyll-include-cache
